# =============================================================================
# File       : service/ssh/00-high-fortress-user.conf
# Updated at : 2026-10-05
# Creator    : palarchsys
# =============================================================================

PermitRootLogin no
PubkeyAuthentication yes
PasswordAuthentication yes
KbdInteractiveAuthentication no

UsePAM yes
Banner /etc/ssh/sshd_banner

LogLevel VERBOSE

MaxAuthTries 4
ClientAliveInterval 300
ClientAliveCountMax 2
LoginGraceTime 30

IgnoreRhosts yes
PermitEmptyPasswords no
PermitUserEnvironment no
HostbasedAuthentication no

X11Forwarding no
AllowTcpForwarding yes
AllowAgentForwarding yes
PermitTunnel no

StrictModes yes
MaxStartups 10:30:60
MaxSessions 10
DebianBanner no
