# =============================================================================
# File       : service/aide/aide.conf
# Updated at : 2026-10-05
# Creator    : palarchsys
# =============================================================================

database_in=file:/var/lib/aide/aide.db
database_out=file:/var/lib/aide/aide.db.new
gzip_dbout=yes

All = p+i+n+u+g+s+b+acl+xattrs+sha512+sha256

/bin                            All
/sbin                           All
/usr/bin                        All
/usr/sbin                       All
/boot                           All
/lib                            All
/lib64                          All
/usr/lib                        All
/usr/lib64                      All
/etc                            All
__HF_BASE__                     All

!/opt/.*/data/
!/var/log/
!/var/cache/
!/var/tmp/
!/var/lib/docker/
!/var/lib/containerd/
!/var/lib/libvirt/
!/opt/brave.com/
!/usr/share/discord/
!/var/lib/snapd/
!/var/lib/flatpak/
!/snap/
!/proc/
!/sys/
!/dev/
!/run/
!/tmp/
!/home/
!/root/.cache/
!/root/.local/

!__HF_BASE__/cron/security_logs($|/)
!__HF_BASE__/cron/cron_logs($|/)
!__HF_BASE__/cron/alerts($|/)
